---
title: "Greg Chism's CV"
author: Greg Chism
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
  cache_data:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("CV_printing_functions.R")

# Read in all data and initialize a CV printer object
# CV <- create_CV_object(
#   data_location = "https://docs.google.com/spreadsheets/d/1JeUL4uGOdpvpGP2jDXWQuHL-IpTdDztiWxSP4qavlKE/edit#gid=917338460",  
#   pdf_mode = params$pdf_mode,
#   cache_data = params$cache_data
# )

CV <- readr::read_rds('cached_positions.rds')

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
if(params$pdf_mode){
  cat("View this CV online with links at https://gchism.netlify.app/uploads/gchism_cv.pdf")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/Gchism94/cv/raw/master/gchism_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Relevant Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available on [github.com/Gchism94/cv](https://github.com/Gchism94/cv).

Last updated on `r Sys.Date()`.



Main
================================================================================

Greg Chism {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('Education')
```

Certifications {data-icon=certificate}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('Certifications')
```


Related Work Experience {data-icon=briefcase}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('industry_experience_aside')
```
:::

```{r}
CV %<>% print_section('Relavant_Work_Experience')
```


Teaching and Mentorship {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('teaching_experience_aside')
```
:::

```{r}
CV %<>% print_section('Teaching_and_Mentorship')
```




<!-- These breaks just force a new page so section doesn't get cut off -->
<br>
<br>
<br>

Professional Development {data-icon=user-tie}
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('Professional_Development')
```


<i class="fab fa-jedi-order"></i> Published Research Compendium  
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('Published_Compendium')
```

<!-- These breaks just force a new page so section doesn't get cut off -->
<br>
<br>
<br>


Publications {data-icon=book}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('data_science_writing_aside')
```
:::

```{r}
CV %<>% print_section('Publications')
```


Published Datasets {data-icon=database}
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('Published_Datasets')
```


Outreach and Service {data-icon=handshake}
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('Outreach_Service')
```


<i class="fas fa-chalkboard"></i> Invited Talks 
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('Invited_Talks')
```


Selected Awards {data-icon=money-bill}
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('Fellowships_Awards')
```

